services:
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db-ah-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=do_eat_db 

volumes:
  db-ah-data: